### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ashwinvaidya17** [samson6460/tf.keras-gradcamplusplus#1]
Hi, I am interested in using your code for my project. Can you provide a license file for your code?

**Comment by samson6460** [comment]
OK, I've provided a license. I hope it is helpful to your research.

**Comment by samson6460** [comment]
> Hi, I am interested in using your code for my project. Can you provide a license file for your code?

OK, I've provided a license. I hope it is helpful to your research.

**Comment by ashwinvaidya17** [comment]
Thank You
